export enum RequestStateEnum {
  INITIALIZING = "INITIALIZING",
  LOADING = "LOADING",
  RETRYING = "RETRYING",
  READY = "READY",
  REQUEST_ACCEPTED = "REQUEST_ACCEPTED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  EVENT_PROCESSED = "EVENT_PROCESSED",
  EVENT_PROCESSING_TIMEOUT = "EVENT_PROCESSING_TIMEOUT",
}
