export enum StateEnum {
  DORMANT = "DORMANT",
  INITIALIZING = "INITIALIZING",
  LOADING = "LOADING",
  REQUESTING = "REQUESTING",
  RETRYING = "RETRYING",
  READY = "READY",
  REQUEST_ACCEPTED = "REQUEST_ACCEPTED",
  REQUEST_COMPLETED = "REQUEST_COMPLETED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  EVENT_PROCESSED = "EVENT_PROCESSED",
  EVENT_PROCESSING_TIMEOUT = "EVENT_PROCESSING_TIMEOUT",
}

export function getAllStateEnums() {
  return [
    StateEnum.DORMANT,
    StateEnum.INITIALIZING,
    StateEnum.LOADING,
    StateEnum.REQUESTING,
    StateEnum.RETRYING,
    StateEnum.READY,
    StateEnum.REQUEST_ACCEPTED,
    StateEnum.REQUEST_COMPLETED,
    StateEnum.REQUEST_REJECTED,
    StateEnum.REQUEST_TIMEOUT,
    StateEnum.EVENT_PROCESSED,
    StateEnum.EVENT_PROCESSING_TIMEOUT,
  ];
}
