apiVersion: apps/v1
kind: Deployment
metadata:
  name: grouphq-ui
  labels:
    app: grouphq-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grouphq-ui
  template:
    metadata:
      labels:
        app: grouphq-ui
    spec:
      containers:
        - name: grouphq-ui
          image: ghcr.io/grouphq/grouphq-ui:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 4200
          env:
            - name: PORT
              value: "4200"
          volumeMounts:
            - name: grouphq-ui-config-volume
              mountPath: /workspace/grouphq-ui/config
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: grouphq-ui-config-volume
          configMap:
            name: grouphq-ui-config
