apiVersion: apps/v1
kind: Deployment
metadata:
  name: grouphq-ui
  labels:
    app: grouphq-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grouphq-ui
  template:
    metadata:
      labels:
        app: grouphq-ui
    spec:
      containers:
        - name: grouphq-ui
          image: grouphq-ui
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9004
          env:
            - name: PORT
              value: "9004"
      imagePullSecrets:
        - name: ghcr-secret
