apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: grouphq-ui-config
    files:
      - config.json
    options:
      labels:
        app: grouphq-ui
