export enum StatesEnum {
  LOADING = "LOADING",
  READY = "READY",
  NEUTRAL = "NEUTRAL",
  HTTP_INTERNAL_SERVER_ERROR = "HTTP_INTERNAL_SERVER_ERROR",
  WEB_SOCKET_CONNECTION_ERROR = "WEB_SOCKET_CONNECTION_ERROR",
}
