#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx ng lint
npx stylelint "**/*.css"
npx stylelint "**/*.scss"
npx prettier . --check # Replace --check with --write to apply changes
npm audit --audit-level high