name: Delivery Stage
on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]
    branches: main
concurrency: deliver

env:
  OWNER: grouphq
  REGISTRY: ghcr.io
  APP_REPO: grouphq-ui
  DEPLOY_REPO: grouphq-deployment
  VERSION: ${{ github.sha }}

jobs:
  deliver:
    name: Deliver release candidate to production
    runs-on: ubuntu-22.04
    steps:
      - name: Deliver application to production
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ env.OWNER }}/${{ env.DEPLOY_REPO }}
          event-type: app_delivery
          client-payload: '{
            "app_image":
            "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.APP_REPO }}",
            "app_name": "${{ env.APP_REPO }}",
            "app_version": "${{ env.VERSION }}"
            }'
